DROP DATABASE IF EXISTS hsj;
CREATE DATABASE hsj;

USE hsj;


DROP TABLE IF EXISTS counter;
CREATE TABLE counter (
    id INT PRIMARY KEY AUTO_INCREMENT,
    value INT NOT NULL DEFAULT 0
);

SELECT * FROM counter;
